package br.com.hs.nfe.ws.br.homo.sceconsultarfb;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 2.2.1
 * Sun Aug 28 20:55:23 BRT 2011
 * Generated source version: 2.2.1
 * 
 */
 
@WebService(targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/SCEConsultaRFB", name = "SCEConsultaRFBSoap")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SCEConsultaRFBSoap {

    @WebResult(name = "sceConsultaDPECResult", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/SCEConsultaRFB", partName = "sceConsultaDPECResult")
    @WebMethod(action = "http://www.portalfiscal.inf.br/nfe/wsdl/SCEConsultaRFB/sceConsultaDPEC")
    public br.inf.portalfiscal.nfe.wsdl.sceConsultaRFB.SceConsultaDPECResultDocument sceConsultaDPEC(
        @WebParam(partName = "sceDadosMsg", name = "sceDadosMsg", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/SCEConsultaRFB")
        br.inf.portalfiscal.nfe.wsdl.sceConsultaRFB.SceDadosMsgDocument sceDadosMsg,
        @WebParam(partName = "sceCabecMsg", mode = WebParam.Mode.INOUT, name = "sceCabecMsg", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/SCEConsultaRFB", header = true)
        javax.xml.ws.Holder<br.inf.portalfiscal.nfe.wsdl.sceConsultaRFB.SceCabecMsgDocument> sceCabecMsg
    );
}
