package br.com.hs.cte.ws.sc.prod.cteconsulta;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 2.2.1
 * Fri Sep 30 14:46:01 BRT 2011
 * Generated source version: 2.2.1
 * 
 */
 
@WebService(targetNamespace = "http://www.portalfiscal.inf.br/cte/wsdl/CteConsulta", name = "CteConsultaSoap12")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CteConsultaSoap12 {

    @WebResult(name = "cteConsultaCTResult", targetNamespace = "http://www.portalfiscal.inf.br/cte/wsdl/CteConsulta", partName = "cteConsultaCTResult")
    @WebMethod(action = "http://www.portalfiscal.inf.br/cte/wsdl/CteConsulta/cteConsultaCT")
    public br.inf.portalfiscal.cte.wsdl.cteConsulta.CteConsultaCTResultDocument cteConsultaCT(
        @WebParam(partName = "cteDadosMsg", name = "cteDadosMsg", targetNamespace = "http://www.portalfiscal.inf.br/cte/wsdl/CteConsulta")
        br.inf.portalfiscal.cte.wsdl.cteConsulta.CteDadosMsgDocument cteDadosMsg,
        @WebParam(partName = "cteCabecMsg", mode = WebParam.Mode.INOUT, name = "cteCabecMsg", targetNamespace = "http://www.portalfiscal.inf.br/cte/wsdl/CteConsulta", header = true)
        javax.xml.ws.Holder<br.inf.portalfiscal.cte.wsdl.cteConsulta.CteCabecMsgDocument> cteCabecMsg
    );
}
