
/*
 * 
 */

package br.com.hs.cte.ws.sc.homo.cteconsulta;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.2.1
 * Wed Sep 28 15:09:44 BRT 2011
 * Generated source version: 2.2.1
 * 
 */


@WebServiceClient(name = "CteConsulta", 
                  wsdlLocation = "file:cteconsulta.wsdl",
                  targetNamespace = "http://www.portalfiscal.inf.br/cte/wsdl/CteConsulta") 
public class CteConsulta extends Service {

    public final static URL WSDL_LOCATION = Thread.currentThread().getContextClassLoader().getResource("wsdl/sc/homo/CteConsultaHomoSC.wsdl");;
    public final static QName SERVICE = new QName("http://www.portalfiscal.inf.br/cte/wsdl/CteConsulta", "CteConsulta");
    public final static QName CteConsultaSoap12 = new QName("http://www.portalfiscal.inf.br/cte/wsdl/CteConsulta", "CteConsultaSoap12");

    public CteConsulta(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CteConsulta(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CteConsulta() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns CteConsultaSoap12
     */
    @WebEndpoint(name = "CteConsultaSoap12")
    public CteConsultaSoap12 getCteConsultaSoap12() {
        return super.getPort(CteConsultaSoap12, CteConsultaSoap12.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CteConsultaSoap12
     */
    @WebEndpoint(name = "CteConsultaSoap12")
    public CteConsultaSoap12 getCteConsultaSoap12(WebServiceFeature... features) {
        return super.getPort(CteConsultaSoap12, CteConsultaSoap12.class, features);
    }

}
