package br.com.hs.nfe.entity;
// Generated Jun 23, 2011 11:18:04 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Nfe generated by hbm2java
 */
public class Nfe  implements java.io.Serializable {
	
	private static final long serialVersionUID = -3557801465452373826L;
	/*
	 * Danfe, TRANSFERIR PARA NotaFiscalConstants
	 */

	public static final char DANFE_IMPRESSO = '1';
	public static final char DANFE_NAO_IMPRESSO = '0';
	
	public static final char EMAIL_ENVIADO = '1';
	public static final char EMAIL_NAO_ENVIADO = '0';
	
     private String chaveAcesso;
     private Character txtValido;
     private Character xmlAssinado;
     private Character xmlValido;
     private String nrec;
     private Character xmlEnviado;
     private String nprot;
     private String cstat;
     private String xmotivo;
     private Character danfeImpresso;
     private Character emailEnviado;
     private Character danfeGerado;
     private String cnpj;
     private Character txtRetornoGerado;
     private Character txtRecebido;
     private Character xmlProcessado;
     private Date dhRecbto;
     private Character xmlCompactado;
     private String pe;
     private int serie;
     private int nnf;
     private Character xmlCancelado;
     private String dest;
     private int codEstabelecimento;
     private String xjust;
     private String email;
     private String numeroCopias;
     private Character tpEmis;
     private Character dpecGerado;
     private Character dpecAssinado;
     private Character dpecValido;
     private Character dpecEnviado;
     private Character dpecProcessado;
     private Character tpAmb;
     private Character dpecCompactado;
     private Character dpecDanfeGerado;
     private Character fsdaPreparado;
     private Character fsdaProcessado;
     private Character fsdaDanfeGerado;
     private Character fsdaCompactado;
     private Character txtRetornoDpecGerado;
     private Character dpecEmailEnviado;
     private String cuf;
     private Character fsdaImpresso;
     private Character zipEnviado;
     private Character consultaEventos;
     private String checksum;
     private Character xmlPersistido;
     private Character cancelarNota;
     

	public Nfe() {
    }
	
    public Nfe(String chaveAcesso) {
        this.chaveAcesso = chaveAcesso;
    }
    public Nfe(String chaveAcesso, Character txtValido, Character xmlAssinado, Character xmlValido, String nrec, Character xmlEnviado, String nprot, String cstat, String xmotivo, Character danfeImpresso, Character emailEnviado, Character danfeGerado, String cnpj, Character txtRetornoGerado, Character txtRecebido, Character xmlProcessado, Date dhRecbto, Character xmlCompactado, String pe,int serie,int nnf,Character xmlCancelado,String dest,int codEstabelecimento,String xjust,String email,String numeroCopias,Character tpEmis,Character dpecGerado,Character dpecAssinado,Character dpecValido,Character dpecEnviado,Character dpecProcessado,Character tpAmb,Character dpecCompactado,Character dpecDanfeGerado,Character fsdaPreparado,Character fsdaProcessado,Character fsdaDanfeGerado,Character fsdaCompactado,Character txtRetornoDpecGerado,Character dpecEmailEnviado,String cUF,Character fsdaImpresso,Character zipEnviado,Character consultaEventos,String checksum,Character xmlPersistido,Character cancelarNota) {
       this.chaveAcesso = chaveAcesso;
       this.txtValido = txtValido;
       this.xmlAssinado = xmlAssinado;
       this.xmlValido = xmlValido;
       this.nrec = nrec;
       this.xmlEnviado = xmlEnviado;
       this.nprot = nprot;
       this.cstat = cstat;
       this.xmotivo = xmotivo;
       this.danfeImpresso = danfeImpresso;
       this.emailEnviado = emailEnviado;
       this.danfeGerado = danfeGerado;
       this.cnpj = cnpj;
       this.txtRetornoGerado = txtRetornoGerado;
       this.txtRecebido = txtRecebido;
       this.xmlProcessado = xmlProcessado;
       this.dhRecbto = dhRecbto;
       this.xmlCompactado = xmlCompactado;
       this.pe = pe;
       this.serie = serie;
       this.nnf = nnf;
       this.xmlCancelado = xmlCancelado;
       this.dest = dest;
       this.codEstabelecimento = codEstabelecimento;
       this.xjust = xjust;
       this.email = email;
       this.numeroCopias = numeroCopias;
       this.tpEmis = tpEmis;
       this.dpecGerado = dpecGerado;
       this.dpecAssinado = dpecAssinado;
       this.dpecValido = dpecValido;
       this.dpecEnviado = dpecEnviado;
       this.dpecProcessado = dpecProcessado;
       this.tpAmb = tpAmb;
       this.dpecCompactado = dpecCompactado;
       this.dpecDanfeGerado = dpecDanfeGerado;
       this.fsdaPreparado = fsdaPreparado;
       this.fsdaProcessado = fsdaProcessado;
       this.fsdaDanfeGerado = fsdaDanfeGerado;
       this.fsdaCompactado = fsdaCompactado;
       this.txtRetornoDpecGerado = txtRetornoDpecGerado;
       this.dpecEmailEnviado = dpecEmailEnviado;
       this.cuf = cUF;
       this.fsdaImpresso = fsdaImpresso;
       this.zipEnviado = zipEnviado;
       this.consultaEventos = consultaEventos;
       this.checksum = checksum;
       this.xmlPersistido = xmlPersistido;
       this.cancelarNota = cancelarNota;
    }
    public String getChaveAcesso() {
        return this.chaveAcesso;
    }
    public void setChaveAcesso(String chaveAcesso) {
        this.chaveAcesso = chaveAcesso;
    }
    public Character getTxtValido() {
        return this.txtValido;
    }
    public void setTxtValido(Character txtValido) {
        this.txtValido = txtValido;
    }
    public Character getXmlAssinado() {
        return this.xmlAssinado;
    }
    public void setXmlAssinado(Character xmlAssinado) {
        this.xmlAssinado = xmlAssinado;
    }
    public Character getXmlValido() {
        return this.xmlValido;
    }
    public void setXmlValido(Character xmlValido) {
        this.xmlValido = xmlValido;
    }
    public String getNrec() {
        return this.nrec;
    }
    public void setNrec(String nrec) {
        this.nrec = nrec;
    }
    public Character getXmlEnviado() {
        return this.xmlEnviado;
    }
    public void setXmlEnviado(Character xmlEnviado) {
        this.xmlEnviado = xmlEnviado;
    }
    public String getNprot() {
        return this.nprot;
    }
    public void setNprot(String nprot) {
        this.nprot = nprot;
    }
    public String getCstat() {
        return this.cstat;
    }
    public void setCstat(String cstat) {
        this.cstat = cstat;
    }
    public String getXmotivo() {
        return this.xmotivo;
    }
    public void setXmotivo(String xmotivo) {
        this.xmotivo = xmotivo;
    }
    public Character getDanfeImpresso() {
        return this.danfeImpresso;
    }
    public void setDanfeImpresso(Character danfeImpresso) {
        this.danfeImpresso = danfeImpresso;
    }
    public Character getEmailEnviado() {
        return this.emailEnviado;
    }
    public void setEmailEnviado(Character emailEnviado) {
        this.emailEnviado = emailEnviado;
    }
    public Character getDanfeGerado() {
        return this.danfeGerado;
    }
    public void setDanfeGerado(Character danfeGerado) {
        this.danfeGerado = danfeGerado;
    }
    public String getCnpj() {
        return this.cnpj;
    }
    public void setCnpj(String cnpj) {
        this.cnpj = cnpj;
    }
    public Character getTxtRetornoGerado() {
        return this.txtRetornoGerado;
    }
    public void setTxtRetornoGerado(Character txtRetornoGerado) {
        this.txtRetornoGerado = txtRetornoGerado;
    }
    public Character getTxtRecebido() {
        return this.txtRecebido;
    }
    public void setTxtRecebido(Character txtRecebido) {
        this.txtRecebido = txtRecebido;
    }
    public Character getXmlProcessado() {
        return this.xmlProcessado;
    }
    public void setXmlProcessado(Character xmlProcessado) {
        this.xmlProcessado = xmlProcessado;
    }
    public Date getDhRecbto() {
        return this.dhRecbto;
    }
    public void setDhRecbto(Date dhRecbto) {
        this.dhRecbto = dhRecbto;
    }
	public Character getXmlCompactado() {
		return xmlCompactado;
	}
	public void setXmlCompactado(Character xmlCompactado) {
		this.xmlCompactado = xmlCompactado;
	}
	public String getPe() {
		return this.pe;
	}
	public void setPe(String pe) {
		this.pe = pe;
	}


	public int getSerie() {
		return serie;
	}


	public void setSerie(int serie) {
		this.serie = serie;
	}


	public int getNnf() {
		return this.nnf;
	}


	public void setNnf(int nf) {
		this.nnf = nf;
	}


	public Character getXmlCancelado() {
		return xmlCancelado;
	}


	public void setXmlCancelado(Character xmlCancelado) {
		this.xmlCancelado = xmlCancelado;
	}

	public String getDest() {
		return dest;
	}

	public void setDest(String dest) {
		this.dest = dest;
	}

	public int getCodEstabelecimento() {
		return codEstabelecimento;
	}

	public void setCodEstabelecimento(int codEstabelecimento) {
		this.codEstabelecimento = codEstabelecimento;
	}

	public String getXjust() {
		return xjust;
	}

	public void setXjust(String xjust) {
		this.xjust = xjust;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getNumeroCopias() {
		return numeroCopias;
	}

	public void setNumeroCopias(String numeroCopias) {
		this.numeroCopias = numeroCopias;
	}

	public Character getTpEmis() {
		return tpEmis;
	}

	public void setTpEmis(Character tpEmis) {
		this.tpEmis = tpEmis;
	}

	public Character getDpecGerado() {
		return dpecGerado;
	}
	
	public void setDpecGerado(Character dpecGerado) {
		this.dpecGerado = dpecGerado;
	}
	public Character getDpecAssinado() {
		return dpecAssinado;
	}

	public void setDpecAssinado(Character dpecAssinado) {
		this.dpecAssinado = dpecAssinado;
	}

	public Character getDpecValido() {
		return dpecValido;
	}

	public void setDpecValido(Character dpecValido) {
		this.dpecValido = dpecValido;
	}

	public Character getDpecEnviado() {
		return dpecEnviado;
	}

	public void setDpecEnviado(Character dpecEnviado) {
		this.dpecEnviado = dpecEnviado;
	}

	public Character getDpecProcessado() {
		return dpecProcessado;
	}

	public void setDpecProcessado(Character dpecProcessado) {
		this.dpecProcessado = dpecProcessado;
	}

	public Character getTpAmb() {
		return tpAmb;
	}

	public void setTpAmb(Character tpAmb) {
		this.tpAmb = tpAmb;
	}

	public Character getDpecCompactado() {
		return dpecCompactado;
	}

	public void setDpecCompactado(Character dpecCompactado) {
		this.dpecCompactado = dpecCompactado;
	}

	public Character getDpecDanfeGerado() {
		return dpecDanfeGerado;
	}

	public void setDpecDanfeGerado(Character dpecDanfeGerado) {
		this.dpecDanfeGerado = dpecDanfeGerado;
	}

	public Character getFsdaPreparado() {
		return fsdaPreparado;
	}

	public void setFsdaPreparado(Character fsdaPreparado) {
		this.fsdaPreparado = fsdaPreparado;
	}

	public Character getFsdaProcessado() {
		return fsdaProcessado;
	}

	public void setFsdaProcessado(Character fsdaProcessado) {
		this.fsdaProcessado = fsdaProcessado;
	}

	public Character getFsdaDanfeGerado() {
		return fsdaDanfeGerado;
	}

	public void setFsdaDanfeGerado(Character fsdaDanfeGerado) {
		this.fsdaDanfeGerado = fsdaDanfeGerado;
	}

	public Character getFsdaCompactado() {
		return fsdaCompactado;
	}

	public void setFsdaCompactado(Character fsdaCompactado) {
		this.fsdaCompactado = fsdaCompactado;
	}

	public Character getTxtRetornoDpecGerado() {
		return txtRetornoDpecGerado;
	}

	public void setTxtRetornoDpecGerado(Character txtRetornoDpecGerado) {
		this.txtRetornoDpecGerado = txtRetornoDpecGerado;
	}

	public Character getDpecEmailEnviado() {
		return dpecEmailEnviado;
	}

	public void setDpecEmailEnviado(Character dpecEmailEnviado) {
		this.dpecEmailEnviado = dpecEmailEnviado;
	}

	public String getCuf() {
		return cuf;
	}

	public void setCuf(String cuf) {
		this.cuf = cuf;
	}

	public Character getFsdaImpresso() {
		return fsdaImpresso;
	}

	public void setFsdaImpresso(Character fsdaImpresso) {
		this.fsdaImpresso = fsdaImpresso;
	}

	public Character getZipEnviado() {
		return zipEnviado;
	}

	public void setZipEnviado(Character zipEnviado) {
		this.zipEnviado = zipEnviado;
	}

	public Character getConsultaEventos() {
		return consultaEventos;
	}

	public void setConsultaEventos(Character consultaEventos) {
		this.consultaEventos = consultaEventos;
	}

	public String getChecksum() {
		return checksum;
	}

	public void setChecksum(String checksum) {
		this.checksum = checksum;
	}

	public Character getXmlPersistido() {
		return xmlPersistido;
	}

	public void setXmlPersistido(Character xmlPersistido) {
		this.xmlPersistido = xmlPersistido;
	}

	public Character getCancelarNota() {
		return cancelarNota;
	}

	public void setCancelarNota(Character cancelarNota) {
		this.cancelarNota = cancelarNota;
	}
	
}


