package br.com.hs.nfe.entity;

import br.com.hs.nfe.dao.EstabelecimentoDAO;
import br.com.hs.nfe.dao.UsuarioDAO;

// Generated 13/06/2008 11:47:43 by Hibernate Tools 3.2.2.GA

/**
 * UsuarioEstabelecimento generated by hbm2java
 */
public class UsuarioEstabelecimento implements java.io.Serializable {
	
	private static final long serialVersionUID = -6213254416757796762L;
	
	private int codUsuarioEstabelecimento;
	private int codUsuario;
	private int codEstabelecimento;
	private UsuarioEstabelecimentoCP chavePrimaria;
	
	public UsuarioEstabelecimento() {
	}
	
	public int getCodUsuarioEstabelecimento() {
		return this.codUsuarioEstabelecimento;
	}
	
	public void setCodUsuarioEstabelecimento(int codUsuarioEstabelecimento) {
		this.codUsuarioEstabelecimento = codUsuarioEstabelecimento;
	}
	
	public int getCodUsuario() {
		return this.codUsuario;
	}
	
	public void setCodUsuario(int codUsuario) {
		this.codUsuario = codUsuario;
	}
	
	public int getCodEstabelecimento() {
		return this.codEstabelecimento;
	}
	
	public void setCodEstabelecimento(int codEstabelecimento) {
		this.codEstabelecimento = codEstabelecimento;
	}
	
	public UsuarioEstabelecimentoCP getChavePrimaria() {
		return this.chavePrimaria;
	}
	
	public void setChavePrimaria(UsuarioEstabelecimentoCP chavePrimaria) {
		this.chavePrimaria = chavePrimaria;
	}
	
	public Usuario getUsuario() {
		UsuarioDAO dao = new UsuarioDAO();
		return dao.findByCod(codUsuario);
	}
	
	public Estabelecimento getEstabelecimento() {
		EstabelecimentoDAO dao = new EstabelecimentoDAO();
		return dao.findByCod(codEstabelecimento);
	}
}
