
/*
 * 
 */

package br.com.hs.nfe.ws.go.prod.nfecancelamento2;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.2.1
 * Tue Nov 01 11:10:12 BRST 2011
 * Generated source version: 2.2.1
 * 
 */


@WebServiceClient(name = "NfeCancelamento2", 
                  wsdlLocation = "file:NfeCancelamento2GOProd.xml",
                  targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeCancelamento2") 
public class NfeCancelamento2 extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://www.portalfiscal.inf.br/nfe/wsdl/NfeCancelamento2", "NfeCancelamento2");
    public final static QName NfeCancelamentoServicePort = new QName("http://www.portalfiscal.inf.br/nfe/wsdl/NfeCancelamento2", "NfeCancelamentoServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:NfeCancelamento2GOProd.xml");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:NfeCancelamento2GOProd.xml");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public NfeCancelamento2(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public NfeCancelamento2(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NfeCancelamento2() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns NfeCancelamentoService
     */
    @WebEndpoint(name = "NfeCancelamentoServicePort")
    public NfeCancelamentoService getNfeCancelamentoServicePort() {
        return super.getPort(NfeCancelamentoServicePort, NfeCancelamentoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NfeCancelamentoService
     */
    @WebEndpoint(name = "NfeCancelamentoServicePort")
    public NfeCancelamentoService getNfeCancelamentoServicePort(WebServiceFeature... features) {
        return super.getPort(NfeCancelamentoServicePort, NfeCancelamentoService.class, features);
    }

}
