package br.com.hs.nfe.ws.go.prod.nfecancelamento2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 2.2.1
 * Tue Nov 01 11:10:12 BRST 2011
 * Generated source version: 2.2.1
 * 
 */
 
@WebService(targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeCancelamento2", name = "NfeCancelamentoService")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface NfeCancelamentoService {

    @WebResult(name = "nfeCancelamentoNF2Result", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeCancelamento2", partName = "nfeCancelamentoNF2Result")
    @WebMethod(action = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeCancelamento2/nfeCancelamentoNF2")
    public br.inf.portalfiscal.nfe.wsdl.nfeCancelamento2.NfeCancelamentoNF2ResultDocument nfeCancelamentoNF2(
        @WebParam(partName = "nfeCabecMsg", name = "nfeCabecMsg", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeCancelamento2", header = true)
        br.inf.portalfiscal.nfe.wsdl.nfeCancelamento2.NfeCabecMsg nfeCabecMsg,
        @WebParam(partName = "nfeDadosMsg", name = "nfeDadosMsg", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeCancelamento2")
        br.inf.portalfiscal.nfe.wsdl.nfeCancelamento2.NfeDadosMsgDocument nfeDadosMsg
    );
}
