
package br.com.hs.nfe.ws.sc.prod.nferetrecepcao2;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import org.apache.cxf.configuration.jsse.TLSClientParameters;
import org.apache.cxf.endpoint.Client;
import org.apache.cxf.frontend.ClientProxy;
import org.apache.cxf.jaxws.JaxWsProxyFactoryBean;
import org.apache.cxf.transport.http.HTTPConduit;
import org.apache.cxf.xmlbeans.XmlBeansDataBinding;
import org.apache.log4j.Logger;

import br.com.hs.nfe.entity.Estabelecimento;
import br.com.hs.nfe.util.ClientConfig;

/**
 * This class was generated by Apache CXF 2.2.1
 * Tue May 31 22:08:26 BRT 2011
 * Generated source version: 2.2.1
 * 
 */

public final class NfeRetRecepcao2Helper {

	private static final Logger logger = Logger.getLogger("NfeRetRecepcao2Helper");
	private ClientConfig clientConfig = null;
    public NfeRetRecepcao2Helper(Estabelecimento config) {
    	this.clientConfig = new ClientConfig(config);
    }

    public String nfeRetRecepcao2(String nome,String xml) throws Exception {
    	TLSClientParameters tls = new TLSClientParameters();
        try
        {
        	this.clientConfig.configTLS(tls);
        }
        catch(Exception e)
        {
        	logger.error("error ",e);
        }
        JaxWsProxyFactoryBean factory = new JaxWsProxyFactoryBean();
        factory.setServiceClass(NfeRetRecepcao2Soap12.class);
        factory.setAddress("https://nfe.sefazvirtual.rs.gov.br/ws/NfeRetRecepcao/NfeRetRecepcao2.asmx");
        factory.setWsdlURL(NfeRetRecepcao2.WSDL_LOCATION.toString());
        factory.setServiceName(NfeRetRecepcao2.SERVICE);
        factory.setEndpointName(NfeRetRecepcao2.NfeRetRecepcao2Soap12);
        factory.getServiceFactory().setDataBinding(new XmlBeansDataBinding());
        NfeRetRecepcao2Soap12 port = (NfeRetRecepcao2Soap12)factory.create();
        Client client = ClientProxy.getClient(port);
        HTTPConduit http = (HTTPConduit)client.getConduit();
        http.setTlsClientParameters(tls);
        br.inf.portalfiscal.nfe.wsdl.nfeRetRecepcao2.NfeRetRecepcao2ResultDocument _nfeRetRecepcao2__return = null;
        
        try{
	        logger.info("Invoking nfeRetRecepcao2...");
	        xml = xml.substring(xml.indexOf("?>")+2);
	        xml = "<?xml version=\"1.0\" encoding=\"utf-8\"?><nfeDadosMsg xmlns=\"http://www.portalfiscal.inf.br/nfe/wsdl/NfeRetRecepcao2\">"+xml+"</nfeDadosMsg>";
	        br.inf.portalfiscal.nfe.wsdl.nfeRetRecepcao2.NfeDadosMsgDocument _nfeRetRecepcaoLote2_nfeDadosMsg = br.inf.portalfiscal.nfe.wsdl.nfeRetRecepcao2.NfeDadosMsgDocument.Factory.parse(xml);
	        br.inf.portalfiscal.nfe.wsdl.nfeRetRecepcao2.NfeCabecMsgDocument nfeRetRecepcaoLote2_nfeCabecMsg = br.inf.portalfiscal.nfe.wsdl.nfeRetRecepcao2.NfeCabecMsgDocument.Factory.newInstance();
	        br.inf.portalfiscal.nfe.wsdl.nfeRetRecepcao2.NfeCabecMsg _nfeRetRecepcaoLote2_nfeCabecMsgVal = br.inf.portalfiscal.nfe.wsdl.nfeRetRecepcao2.NfeCabecMsg.Factory.newInstance();
	        _nfeRetRecepcaoLote2_nfeCabecMsgVal.setCUF("42");
	        _nfeRetRecepcaoLote2_nfeCabecMsgVal.setVersaoDados("2.00");
	        nfeRetRecepcaoLote2_nfeCabecMsg.setNfeCabecMsg(_nfeRetRecepcaoLote2_nfeCabecMsgVal);
	        
	        
	        javax.xml.ws.Holder<br.inf.portalfiscal.nfe.wsdl.nfeRetRecepcao2.NfeCabecMsgDocument> _nfeRetRecepcao2_nfeCabecMsg = new javax.xml.ws.Holder<br.inf.portalfiscal.nfe.wsdl.nfeRetRecepcao2.NfeCabecMsgDocument>(nfeRetRecepcaoLote2_nfeCabecMsg);
	        _nfeRetRecepcao2__return = port.nfeRetRecepcao2(_nfeRetRecepcaoLote2_nfeDadosMsg, _nfeRetRecepcao2_nfeCabecMsg);
	        logger.info("nfeRetRecepcao2.result=" + _nfeRetRecepcao2__return);

	        logger.info("nfeRetRecepcao2._nfeRetRecepcao2_nfeCabecMsg=" + _nfeRetRecepcao2_nfeCabecMsg.value);

        }
        catch(Exception e)
        {
        	logger.error("error ",e);
        }
        return _nfeRetRecepcao2__return.toString();
    }

}
