
/*
 * 
 */

package br.com.hs.nfe.ws.go.homo.nfestatusservico2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.1
 * Mon Oct 31 17:43:56 BRST 2011
 * Generated source version: 2.2.1
 * 
 */


@WebServiceClient(name = "NfeStatusServico2", 
                  wsdlLocation = "file:NfeStatusServico2GOHomo.xml",
                  targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeStatusServico2") 
public class NfeStatusServico2 extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://www.portalfiscal.inf.br/nfe/wsdl/NfeStatusServico2", "NfeStatusServico2");
    public final static QName NfeStatusServicoServicePort = new QName("http://www.portalfiscal.inf.br/nfe/wsdl/NfeStatusServico2", "NfeStatusServicoServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:NfeStatusServico2GOHomo.xml");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:NfeStatusServico2GOHomo.xml");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public NfeStatusServico2(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public NfeStatusServico2(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NfeStatusServico2() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns NfeStatusServicoService
     */
    @WebEndpoint(name = "NfeStatusServicoServicePort")
    public NfeStatusServicoService getNfeStatusServicoServicePort() {
        return super.getPort(NfeStatusServicoServicePort, NfeStatusServicoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NfeStatusServicoService
     */
    @WebEndpoint(name = "NfeStatusServicoServicePort")
    public NfeStatusServicoService getNfeStatusServicoServicePort(WebServiceFeature... features) {
        return super.getPort(NfeStatusServicoServicePort, NfeStatusServicoService.class, features);
    }

}
