package br.com.hs.nfe;

import java.rmi.RMISecurityManager;

import org.apache.log4j.Logger;
import org.apache.log4j.PropertyConfigurator;

import br.com.hs.evt.envevento.ConsSitNFe21Thread;
import br.com.hs.evt.envevento.ConsSitNFeEntrada21Thread;
import br.com.hs.evt.envevento.EnvEventoAssinadorThread;
import br.com.hs.evt.envevento.EnvEventoConfirmacaoRecebimentoThread;
import br.com.hs.evt.envevento.EnvEventoEnviadorThread;
import br.com.hs.evt.envevento.EnvEventoThread;
import br.com.hs.evt.envevento.EnvEventoValidadorThread;
import br.com.hs.nfe.cancnfe.CancNFeAssinadorThread;
import br.com.hs.nfe.cancnfe.CancNFeEnviadorThread;
import br.com.hs.nfe.cancnfe.CancNFeThread;
import br.com.hs.nfe.cancnfe.CancNFeValidadorThread;
import br.com.hs.nfe.cancnfe.GerarPedidoCancelamentoThread;
import br.com.hs.nfe.cancproc.CancProcThread;
import br.com.hs.nfe.cert.VerificaValidadeCertificadoDigitalA1Thread;
import br.com.hs.nfe.conf.Estabelecs;
import br.com.hs.nfe.conf.PropriedadesSistema;
import br.com.hs.nfe.consdpec.ConsDpecThread;
import br.com.hs.nfe.consrecinfe.ConsReciNFeThread;
import br.com.hs.nfe.conssit.ConsSitNFeEntradaThread;
import br.com.hs.nfe.conssit.ConsSitNFeThread;
import br.com.hs.nfe.cte.ConsSitCteThread;
import br.com.hs.nfe.cte.ReciCteValidadorThread;
import br.com.hs.nfe.dpec.EnvDpecAssinadorThread;
import br.com.hs.nfe.dpec.EnvDpecEnviadorThread;
import br.com.hs.nfe.dpec.EnvDpecReenviaNFeThread;
import br.com.hs.nfe.dpec.EnvDpecValidadorThread;
import br.com.hs.nfe.dpecproc.DpecProcThread;
import br.com.hs.nfe.email.EmailCancThread;
import br.com.hs.nfe.email.EmailCteThread;
import br.com.hs.nfe.email.EmailDpecThread;
import br.com.hs.nfe.email.EmailEntradaThread;
import br.com.hs.nfe.email.EmailThread;
import br.com.hs.nfe.entity.Estabelecimento;
import br.com.hs.nfe.envinfe.EnviNFeAssinadorThread;
import br.com.hs.nfe.envinfe.EnviNFeEnviadorThread;
import br.com.hs.nfe.envinfe.EnviNFeThread;
import br.com.hs.nfe.envinfe.EnviNFeValidadorThread;
import br.com.hs.nfe.fsda.EnvFsdaReenviaNFeThread;
import br.com.hs.nfe.fsda.FSDAProcThread;
import br.com.hs.nfe.fsda.PreparaFSDAThread;
import br.com.hs.nfe.inutnfe.InutNFeAssinadorThread;
import br.com.hs.nfe.inutnfe.InutNFeEnviadorThread;
import br.com.hs.nfe.inutnfe.InutNFeThread;
import br.com.hs.nfe.inutnfe.InutNFeValidadorThread;
import br.com.hs.nfe.nfeproc.NFeProcThread;
import br.com.hs.nfe.pdf.DanfeDpecThread;
import br.com.hs.nfe.pdf.DanfeEntradaThread;
import br.com.hs.nfe.pdf.DanfeFsdaThread;
import br.com.hs.nfe.pdf.DanfeThread;
import br.com.hs.nfe.pe.file.DpecSenderThread;
import br.com.hs.nfe.pe.file.FileSenderThread;
import br.com.hs.nfe.pe.file.FsdaManualSenderThread;
import br.com.hs.nfe.pe.file.FsdaSenderThread;
import br.com.hs.nfe.percxml.PercXMLThread;
import br.com.hs.nfe.print.ImprimirFsdaThread;
import br.com.hs.nfe.print.ImprimirPDFThread;
import br.com.hs.nfe.recinfe.ReciNFeValidadorThread;
import br.com.hs.nfe.signer.CarregaCertificadoA3;
import br.com.hs.nfe.xslt.XsltCancToTxtThread;
import br.com.hs.nfe.xslt.XsltDpecToTxtThread;
import br.com.hs.nfe.xslt.XsltEventoEntradaToTxtThread;
import br.com.hs.nfe.xslt.XsltEventoToTxtThread;
import br.com.hs.nfe.xslt.XsltInutToTxtThread;
import br.com.hs.nfe.xslt.XsltNFeEntradaToTxtThread;
import br.com.hs.nfe.xslt.XsltNFeToDpecThread;
import br.com.hs.nfe.xslt.XsltNFeToTxtThread;
import br.com.hs.nfe.zip.CompactaDpecThread;
import br.com.hs.nfe.zip.CompactaFsdaThread;
import br.com.hs.nfe.zip.CompactaNFeThread;

public class Main
{
	private static final Logger logger = Logger.getLogger("Main");
	public static void main(String... args)
	{
		String log4jConfigurationFile = System.getProperty("log4j.configuration", "../resources/log4j.properties");
		PropertyConfigurator.configure(log4jConfigurationFile);
		logger.info("Aplicação iniciada");
		if(System.getSecurityManager() == null) 
		{
		     System.setSecurityManager(new RMISecurityManager());
		}
		if(PropriedadesSistema.getInstance().getSistema().getUsarProxy()=='S')
		{
			System.setProperty("http.proxySet", "true"); 
			System.setProperty("http.proxyHost", PropriedadesSistema.getInstance().getSistema().getServidorProxy());  
			System.setProperty("http.proxyPort", PropriedadesSistema.getInstance().getSistema().getPortaServidorProxy());  
			System.setProperty("http.proxyType", "4");  
			System.setProperty("http.proxyUser", PropriedadesSistema.getInstance().getSistema().getUsuarioProxy());
			System.setProperty("http.proxyPassword", PropriedadesSistema.getInstance().getSistema().getSenhaUsuarioProxy()); 
		}
	    
		for(Estabelecimento config:Estabelecs.getInstance().pes)
		{
			EnviNFeThread enviNFeThread = new EnviNFeThread(config);
			enviNFeThread.start();
			CancNFeThread cancNFeThread = new CancNFeThread(config);
			cancNFeThread.start();
			InutNFeThread inutNFeThread = new InutNFeThread(config);
			inutNFeThread.start();
			CarregaCertificadoA3 carregaCertificadoA3 = new CarregaCertificadoA3(config);
			carregaCertificadoA3.start();
			EnviNFeAssinadorThread enviNFeAssinadorThread = new EnviNFeAssinadorThread(config);
			enviNFeAssinadorThread.start();
			CancNFeAssinadorThread cancNFeAssinadorThread = new CancNFeAssinadorThread(config);
			cancNFeAssinadorThread.start();
			InutNFeAssinadorThread inutNFeAssinadorThread = new InutNFeAssinadorThread(config);
			inutNFeAssinadorThread.start();
			EnviNFeValidadorThread enviNFeValidadorThread = new EnviNFeValidadorThread(config);
			enviNFeValidadorThread.start();
			CancNFeValidadorThread cancNFeValidadorThread = new CancNFeValidadorThread(config);
			cancNFeValidadorThread.start();
			InutNFeValidadorThread inutNFeValidadorThread = new InutNFeValidadorThread(config);
			inutNFeValidadorThread.start();
			EnviNFeEnviadorThread enviNFeEnviadorThread = new EnviNFeEnviadorThread(config);
			enviNFeEnviadorThread.start();
			CancNFeEnviadorThread cancNFeEnviadorThread = new CancNFeEnviadorThread(config);
			cancNFeEnviadorThread.start();
			InutNFeEnviadorThread inutNFeEnviadorThread = new InutNFeEnviadorThread(config);
			inutNFeEnviadorThread.start();
			ConsReciNFeThread consReciNFeThread = new ConsReciNFeThread(config);
			consReciNFeThread.start();
			ConsSitNFeThread consSitNFeThread = new ConsSitNFeThread(config);
			consSitNFeThread.start();
			NFeProcThread nfeProcThread = new NFeProcThread(config);
			nfeProcThread.start();
			CancProcThread cancProcThread = new CancProcThread(config);
			cancProcThread.start();
			CompactaNFeThread compactaNFeThread = new CompactaNFeThread(config);
			compactaNFeThread.start();
			PercXMLThread percXMLThread = new PercXMLThread(config);
			percXMLThread.start();
			DanfeThread danfeThread = new DanfeThread(config);
			danfeThread.start();
			EmailThread emailThread = new EmailThread(config);
			emailThread.start();
			EmailCancThread emailCancThread = new EmailCancThread(config);
			emailCancThread.start();
			ImprimirPDFThread imprimirPDFThread = new ImprimirPDFThread(config);
			imprimirPDFThread.start();
			XsltNFeToTxtThread xlstNFeToTxtThread = new XsltNFeToTxtThread(config);
			xlstNFeToTxtThread.start();
			XsltCancToTxtThread xlstCancToTxtThread = new XsltCancToTxtThread(config);
			xlstCancToTxtThread.start();
			XsltInutToTxtThread xlstInutToTxtThread = new XsltInutToTxtThread(config);
			xlstInutToTxtThread.start();
			XsltNFeToDpecThread xsltNFeToDpecThread = new XsltNFeToDpecThread(config);
			xsltNFeToDpecThread.start();
			EnvDpecAssinadorThread envDpecAssinadorThread = new EnvDpecAssinadorThread(config);
			envDpecAssinadorThread.start();
			EnvDpecValidadorThread envDpecValidadorThread = new EnvDpecValidadorThread(config);
			envDpecValidadorThread.start();
			EnvDpecEnviadorThread envDpecEnviadorThread = new EnvDpecEnviadorThread(config);
			envDpecEnviadorThread.start();
			ConsDpecThread consDpecThread = new ConsDpecThread(config);
			consDpecThread.start();
			XsltDpecToTxtThread dpecToTxtThread = new XsltDpecToTxtThread(config);
			dpecToTxtThread.start();
			DpecProcThread dpecProcThread = new DpecProcThread(config);
			dpecProcThread.start();
			CompactaDpecThread compactaDpecThread = new CompactaDpecThread(config);
			compactaDpecThread.start();
			DanfeDpecThread danfeDpecThread = new DanfeDpecThread(config);
			danfeDpecThread.start();
			EmailDpecThread emailDpecThread = new EmailDpecThread(config);
			emailDpecThread.start();
			EnvDpecReenviaNFeThread dpecReenviaNFeThread = new EnvDpecReenviaNFeThread(config);
			dpecReenviaNFeThread.start();
			PreparaFSDAThread preparaFSDAThread = new PreparaFSDAThread(config);
			preparaFSDAThread.start();
			FSDAProcThread fsdaProcThread = new FSDAProcThread(config);
			fsdaProcThread.start();
			CompactaFsdaThread compactaFsdaThread = new CompactaFsdaThread(config);
			compactaFsdaThread.start();
			DanfeFsdaThread danfeFsdaThread = new DanfeFsdaThread(config);
			danfeFsdaThread.start();
			ImprimirFsdaThread imprimirFsdaThread = new ImprimirFsdaThread(config);
			imprimirFsdaThread.start();
			EnvFsdaReenviaNFeThread envFsdaReenviaNFeThread = new EnvFsdaReenviaNFeThread(config);
			envFsdaReenviaNFeThread.start();
			ConsSitNFeEntradaThread consSitNFeEntradaThread = new ConsSitNFeEntradaThread(config);
			consSitNFeEntradaThread.start();
			ConsSitCteThread consSitCteThread = new ConsSitCteThread(config);
			consSitCteThread.start();
			FileSenderThread fileSenderThread = new FileSenderThread(config);
			fileSenderThread.start();
			DpecSenderThread dpecSenderThread = new DpecSenderThread(config);
			dpecSenderThread.start();
			FsdaSenderThread fsdaSenderThread = new FsdaSenderThread(config);
			fsdaSenderThread.start();
			EnvEventoThread envEventoThread = new EnvEventoThread(config);
			envEventoThread.start();
			EnvEventoAssinadorThread envEventoAssinadorThread = new EnvEventoAssinadorThread(config);
			envEventoAssinadorThread.start();
			EnvEventoValidadorThread envEventoValidadorThread = new EnvEventoValidadorThread(config);
			envEventoValidadorThread.start();
			EnvEventoEnviadorThread envEventoEnviadorThread = new EnvEventoEnviadorThread(config);
			envEventoEnviadorThread.start();
			ConsSitNFe21Thread consSitNFe21Thread = new ConsSitNFe21Thread(config);
			consSitNFe21Thread.start();
			XsltEventoToTxtThread xsltEventoToTxtThread = new XsltEventoToTxtThread(config);
			xsltEventoToTxtThread.start();
			ConsSitNFeEntrada21Thread consSitNFeEntrada21Thread = new ConsSitNFeEntrada21Thread(config);
			consSitNFeEntrada21Thread.start();
			VerificaValidadeCertificadoDigitalA1Thread certificadoDigitalA1Thread = new VerificaValidadeCertificadoDigitalA1Thread(config);
			certificadoDigitalA1Thread.start();
			EnvEventoConfirmacaoRecebimentoThread envEventoConfirmacaoRecebimentoThread = new EnvEventoConfirmacaoRecebimentoThread(config);
			envEventoConfirmacaoRecebimentoThread.start();
			FsdaManualSenderThread fsdaManualSenderThread = new FsdaManualSenderThread(config);
			fsdaManualSenderThread.start();
			GerarPedidoCancelamentoThread gerarPedidoCancelamentoThread = new GerarPedidoCancelamentoThread(config);
			gerarPedidoCancelamentoThread.start();
		}
		EmailEntradaThread emailEntradaThread = new EmailEntradaThread();
		emailEntradaThread.start();
		EmailCteThread emailCteThread = new EmailCteThread();
		emailCteThread.start();
		ReciNFeValidadorThread reciNFeValidadorThread = new ReciNFeValidadorThread();
		reciNFeValidadorThread.start();
		ReciCteValidadorThread reciCteValidadorThread = new ReciCteValidadorThread();
		reciCteValidadorThread.start();
		DanfeEntradaThread danfeEntradaThread = new DanfeEntradaThread();
		danfeEntradaThread.start();
		XsltNFeEntradaToTxtThread entradaToTxtThread = new XsltNFeEntradaToTxtThread();
		entradaToTxtThread.start();
		XsltEventoEntradaToTxtThread xsltEventoEntradaToTxtThread = new XsltEventoEntradaToTxtThread();
		xsltEventoEntradaToTxtThread.start();
	}
}
