
/*
 * 
 */

package br.com.hs.nfe.ws.br.prod.scerecepcaorfb;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.2.1
 * Tue Oct 25 10:27:20 BRST 2011
 * Generated source version: 2.2.1
 * 
 */


@WebServiceClient(name = "SCERecepcaoRFB", 
                  wsdlLocation = "file:SCERecepcaoRFB.xml",
                  targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/SCERecepcaoRFB") 
public class SCERecepcaoRFB extends Service {

    public final static URL WSDL_LOCATION = Thread.currentThread().getContextClassLoader().getResource("wsdl/br/prod/SCERecepcaoRFB.wsdl");
    public final static QName SERVICE = new QName("http://www.portalfiscal.inf.br/nfe/wsdl/SCERecepcaoRFB", "SCERecepcaoRFB");
    public final static QName SCERecepcaoRFBSoap12 = new QName("http://www.portalfiscal.inf.br/nfe/wsdl/SCERecepcaoRFB", "SCERecepcaoRFBSoap12");
    public final static QName SCERecepcaoRFBSoap = new QName("http://www.portalfiscal.inf.br/nfe/wsdl/SCERecepcaoRFB", "SCERecepcaoRFBSoap");

    public SCERecepcaoRFB(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SCERecepcaoRFB(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SCERecepcaoRFB() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns SCERecepcaoRFBSoap
     */
    @WebEndpoint(name = "SCERecepcaoRFBSoap12")
    public SCERecepcaoRFBSoap getSCERecepcaoRFBSoap12() {
        return super.getPort(SCERecepcaoRFBSoap12, SCERecepcaoRFBSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SCERecepcaoRFBSoap
     */
    @WebEndpoint(name = "SCERecepcaoRFBSoap12")
    public SCERecepcaoRFBSoap getSCERecepcaoRFBSoap12(WebServiceFeature... features) {
        return super.getPort(SCERecepcaoRFBSoap12, SCERecepcaoRFBSoap.class, features);
    }
    /**
     * 
     * @return
     *     returns SCERecepcaoRFBSoap
     */
    @WebEndpoint(name = "SCERecepcaoRFBSoap")
    public SCERecepcaoRFBSoap getSCERecepcaoRFBSoap() {
        return super.getPort(SCERecepcaoRFBSoap, SCERecepcaoRFBSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SCERecepcaoRFBSoap
     */
    @WebEndpoint(name = "SCERecepcaoRFBSoap")
    public SCERecepcaoRFBSoap getSCERecepcaoRFBSoap(WebServiceFeature... features) {
        return super.getPort(SCERecepcaoRFBSoap, SCERecepcaoRFBSoap.class, features);
    }

}
