
package br.com.hs.nfe.ws.sc.homo.nfeconsulta2;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import org.apache.cxf.configuration.jsse.TLSClientParameters;
import org.apache.cxf.endpoint.Client;
import org.apache.cxf.frontend.ClientProxy;
import org.apache.cxf.jaxws.JaxWsProxyFactoryBean;
import org.apache.cxf.transport.http.HTTPConduit;
import org.apache.cxf.xmlbeans.XmlBeansDataBinding;
import org.apache.log4j.Logger;

import br.com.hs.nfe.entity.Estabelecimento;
import br.com.hs.nfe.util.ClientConfig;

/**
 * This class was generated by Apache CXF 2.2.1
 * Tue May 31 22:14:49 BRT 2011
 * Generated source version: 2.2.1
 * 
 */

public final class NfeConsulta2Helper {
	
	private static final Logger logger = Logger.getLogger("NfeConsulta2Helper");
	private ClientConfig clientConfig = null;
    public NfeConsulta2Helper(Estabelecimento config) {
    	this.clientConfig = new ClientConfig(config);
    }

    public String nfeConsulta2(String xml,String versao) throws Exception {
    	TLSClientParameters tls = new TLSClientParameters();
        try
        {
        	this.clientConfig.configTLS(tls);
        }
        catch(Exception e)
        {
        	logger.error("error ",e);
        }
        JaxWsProxyFactoryBean factory = new JaxWsProxyFactoryBean();
        factory.setServiceClass(NfeConsulta2Soap12.class);
        factory.setAddress("https://homologacao.nfe.sefazvirtual.rs.gov.br/ws/NfeConsulta/NfeConsulta2.asmx");
        factory.setWsdlURL(NfeConsulta2.WSDL_LOCATION.toString());
        factory.setServiceName(NfeConsulta2.SERVICE);
        factory.setEndpointName(NfeConsulta2.NfeConsulta2Soap12);
        factory.getServiceFactory().setDataBinding(new XmlBeansDataBinding());
        NfeConsulta2Soap12 port = (NfeConsulta2Soap12)factory.create();
        Client client = ClientProxy.getClient(port);
        HTTPConduit http = (HTTPConduit)client.getConduit();
        http.setTlsClientParameters(tls);
        br.inf.portalfiscal.nfe.wsdl.nfeConsulta2.NfeConsultaNF2ResultDocument _nfeConsultaNF2__return = null;
        
        try{
        logger.info("Invoking nfeConsultaNF2...");
        xml = xml.substring(xml.indexOf("?>")+2);
        xml = "<?xml version=\"1.0\" encoding=\"utf-8\"?><nfeDadosMsg xmlns=\"http://www.portalfiscal.inf.br/nfe/wsdl/NfeConsulta2\">"+xml+"</nfeDadosMsg>";
        br.inf.portalfiscal.nfe.wsdl.nfeConsulta2.NfeDadosMsgDocument _nfeConsultaNF2_nfeDadosMsg = br.inf.portalfiscal.nfe.wsdl.nfeConsulta2.NfeDadosMsgDocument.Factory.parse(xml);
        br.inf.portalfiscal.nfe.wsdl.nfeConsulta2.NfeCabecMsgDocument nfeConsultaNF2_nfeCabecMsg = br.inf.portalfiscal.nfe.wsdl.nfeConsulta2.NfeCabecMsgDocument.Factory.newInstance(); 
        br.inf.portalfiscal.nfe.wsdl.nfeConsulta2.NfeCabecMsg _nfeConsultaNF2_nfeCabecMsgVal = br.inf.portalfiscal.nfe.wsdl.nfeConsulta2.NfeCabecMsg.Factory.newInstance();
        _nfeConsultaNF2_nfeCabecMsgVal.setCUF("42");
        _nfeConsultaNF2_nfeCabecMsgVal.setVersaoDados(versao);
        nfeConsultaNF2_nfeCabecMsg.setNfeCabecMsg(_nfeConsultaNF2_nfeCabecMsgVal);
        
        javax.xml.ws.Holder<br.inf.portalfiscal.nfe.wsdl.nfeConsulta2.NfeCabecMsgDocument> _nfeConsultaNF2_nfeCabecMsg = new javax.xml.ws.Holder<br.inf.portalfiscal.nfe.wsdl.nfeConsulta2.NfeCabecMsgDocument>(nfeConsultaNF2_nfeCabecMsg);
        _nfeConsultaNF2__return = port.nfeConsultaNF2(_nfeConsultaNF2_nfeDadosMsg, _nfeConsultaNF2_nfeCabecMsg);
        logger.info("nfeConsultaNF2.result=" + _nfeConsultaNF2__return);

        logger.info("nfeConsultaNF2._nfeConsultaNF2_nfeCabecMsg=" + _nfeConsultaNF2_nfeCabecMsg.value);

        }
        catch(Exception e)
        {
        	logger.error("error ",e);
        }

        return _nfeConsultaNF2__return.toString();
    }

}
