
package br.com.hs.nfe.ws.go.homo.nfecancelamento2;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.2.1
 * Mon Oct 31 17:40:54 BRST 2011
 * Generated source version: 2.2.1
 * 
 */

public final class NfeCancelamentoService_NfeCancelamentoServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.portalfiscal.inf.br/nfe/wsdl/NfeCancelamento2", "NfeCancelamento2");

    private NfeCancelamentoService_NfeCancelamentoServicePort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = NfeCancelamento2.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        NfeCancelamento2 ss = new NfeCancelamento2(wsdlURL, SERVICE_NAME);
        NfeCancelamentoService port = ss.getNfeCancelamentoServicePort();  
        
        {
        System.out.println("Invoking nfeCancelamentoNF2...");
        br.inf.portalfiscal.nfe.wsdl.nfeCancelamento2.NfeCabecMsg _nfeCancelamentoNF2_nfeCabecMsg = null;
        br.inf.portalfiscal.nfe.wsdl.nfeCancelamento2.NfeDadosMsgDocument _nfeCancelamentoNF2_nfeDadosMsg = null;
        br.inf.portalfiscal.nfe.wsdl.nfeCancelamento2.NfeCancelamentoNF2ResultDocument _nfeCancelamentoNF2__return = port.nfeCancelamentoNF2(_nfeCancelamentoNF2_nfeCabecMsg, _nfeCancelamentoNF2_nfeDadosMsg);
        System.out.println("nfeCancelamentoNF2.result=" + _nfeCancelamentoNF2__return);


        }

        System.exit(0);
    }

}
