
/*
 * 
 */

package br.com.hs.nfe.ws.sp.homo.cadconsultacadastro2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.1
 * Tue Nov 01 10:21:43 BRST 2011
 * Generated source version: 2.2.1
 * 
 */


@WebServiceClient(name = "CadConsultaCadastro2", 
                  wsdlLocation = "file:CadConsultaCadastro2SPHomo.xml",
                  targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro2") 
public class CadConsultaCadastro2 extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro2", "CadConsultaCadastro2");
    public final static QName CadConsultaCadastro2Soap12 = new QName("http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro2", "CadConsultaCadastro2Soap12");
    static {
        URL url = null;
        try {
            url = new URL("file:CadConsultaCadastro2SPHomo.xml");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:CadConsultaCadastro2SPHomo.xml");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public CadConsultaCadastro2(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CadConsultaCadastro2(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CadConsultaCadastro2() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns CadConsultaCadastro2Soap12
     */
    @WebEndpoint(name = "CadConsultaCadastro2Soap12")
    public CadConsultaCadastro2Soap12 getCadConsultaCadastro2Soap12() {
        return super.getPort(CadConsultaCadastro2Soap12, CadConsultaCadastro2Soap12.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CadConsultaCadastro2Soap12
     */
    @WebEndpoint(name = "CadConsultaCadastro2Soap12")
    public CadConsultaCadastro2Soap12 getCadConsultaCadastro2Soap12(WebServiceFeature... features) {
        return super.getPort(CadConsultaCadastro2Soap12, CadConsultaCadastro2Soap12.class, features);
    }

}
