package br.com.hs.nfe.ws.br.homo.nferetrecepcaoscan;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 2.2.1
 * Mon Sep 05 15:03:31 BRT 2011
 * Generated source version: 2.2.1
 * 
 */
 
@WebService(targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeRetRecepcao2", name = "NfeRetRecepcao2Soap")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface NfeRetRecepcao2Soap {

    @WebResult(name = "nfeRetRecepcao2Result", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeRetRecepcao2", partName = "nfeRetRecepcao2Result")
    @WebMethod(action = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeRetRecepcao2/nfeRetRecepcao2")
    public br.inf.portalfiscal.nfe.wsdl.nfeRetRecepcao2.NfeRetRecepcao2ResultDocument nfeRetRecepcao2(
        @WebParam(partName = "nfeDadosMsg", name = "nfeDadosMsg", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeRetRecepcao2")
        br.inf.portalfiscal.nfe.wsdl.nfeRetRecepcao2.NfeDadosMsgDocument nfeDadosMsg,
        @WebParam(partName = "nfeCabecMsg", name = "nfeCabecMsg", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeRetRecepcao2", header = true)
        br.inf.portalfiscal.nfe.wsdl.nfeRetRecepcao2.NfeCabecMsgDocument nfeCabecMsg
    );
}
