
package br.com.hs.nfe.ws.br.prod.statusservicoscan;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import org.apache.cxf.configuration.jsse.TLSClientParameters;
import org.apache.cxf.endpoint.Client;
import org.apache.cxf.frontend.ClientProxy;
import org.apache.cxf.jaxws.JaxWsProxyFactoryBean;
import org.apache.cxf.transport.http.HTTPConduit;
import org.apache.cxf.xmlbeans.XmlBeansDataBinding;
import org.apache.log4j.Logger;

import br.com.hs.nfe.entity.Estabelecimento;
import br.com.hs.nfe.util.ClientConfig;

/**
 * This class was generated by Apache CXF 2.2.1
 * Mon Sep 05 15:04:20 BRT 2011
 * Generated source version: 2.2.1
 * 
 */

public final class NfeStatusServicoScan2Helper {

	private static final Logger logger = Logger.getLogger("NfeRecepcaoScan2Helper");
    private ClientConfig clientConfig = null;

    public NfeStatusServicoScan2Helper(Estabelecimento config) {
    	clientConfig = new ClientConfig(config);
    }

    public String nfeStatusServicoNFScan2(String xml) throws Exception {
    	
    	TLSClientParameters tls = new TLSClientParameters();
        try
        {
        	this.clientConfig.configTLS(tls);
        }
        catch(Exception e)
        {
        	logger.error("error ",e);
        }
        JaxWsProxyFactoryBean factory = new JaxWsProxyFactoryBean();
        factory.setServiceClass(NfeStatusServico2Soap.class);
        factory.setAddress("https://www.scan.fazenda.gov.br/NfeStatusServico2/NfeStatusServico2.asmx");
        factory.setWsdlURL(NfeStatusServico2.WSDL_LOCATION.toString());
        factory.setServiceName(NfeStatusServico2.SERVICE);
        factory.setEndpointName(NfeStatusServico2.NfeStatusServico2Soap12);
        factory.getServiceFactory().setDataBinding(new XmlBeansDataBinding());
        NfeStatusServico2Soap port = (NfeStatusServico2Soap)factory.create();
        Client client = ClientProxy.getClient(port);
        HTTPConduit http = (HTTPConduit)client.getConduit();
        http.setTlsClientParameters(tls);
        br.inf.portalfiscal.nfe.wsdl.nfeStatusServico2.NfeStatusServicoNF2ResultDocument _nfeStatusServico2__return = null;
        //try{
	        logger.info("Invoking nfeStatusServico2...");
	        //br.inf.portalfiscal.nfe.wsdl.nfeRecepcao2.NfeDadosMsgDocument _nfeStatusServico2_nfeDadosMsg = br.inf.portalfiscal.nfe.wsdl.nfeRecepcao2.NfeDadosMsgDocument.Factory.newInstance();
	        xml = xml.substring(xml.indexOf("?>")+2);
	        xml = "<?xml version=\"1.0\" encoding=\"utf-8\"?><nfeDadosMsg xmlns=\"http://www.portalfiscal.inf.br/nfe/wsdl/NfeStatusServico2\">"+xml+"</nfeDadosMsg>";
	        br.inf.portalfiscal.nfe.wsdl.nfeStatusServico2.NfeDadosMsgDocument _nfeStatusServico2_nfeDadosMsg = br.inf.portalfiscal.nfe.wsdl.nfeStatusServico2.NfeDadosMsgDocument.Factory.parse(xml);
	        br.inf.portalfiscal.nfe.wsdl.nfeStatusServico2.NfeCabecMsgDocument nfeStatusServico2_nfeCabecMsg = br.inf.portalfiscal.nfe.wsdl.nfeStatusServico2.NfeCabecMsgDocument.Factory.newInstance();
	        br.inf.portalfiscal.nfe.wsdl.nfeStatusServico2.NfeCabecMsg _nfeStatusServico2_nfeCabecMsgVal = br.inf.portalfiscal.nfe.wsdl.nfeStatusServico2.NfeCabecMsg.Factory.newInstance();
	        _nfeStatusServico2_nfeCabecMsgVal.setVersaoDados("2.00");
	        _nfeStatusServico2_nfeCabecMsgVal.setCUF("42");
	        nfeStatusServico2_nfeCabecMsg.setNfeCabecMsg(_nfeStatusServico2_nfeCabecMsgVal);
	        //javax.xml.ws.Holder<br.inf.portalfiscal.nfe.wsdl.nfeStatusServico2.NfeCabecMsgDocument> _nfeStatusServico2_nfeCabecMsg = new javax.xml.ws.Holder<br.inf.portalfiscal.nfe.wsdl.nfeStatusServico2.NfeCabecMsgDocument>(nfeStatusServico2_nfeCabecMsg);
	        _nfeStatusServico2__return = port.nfeStatusServicoNF2(_nfeStatusServico2_nfeDadosMsg, nfeStatusServico2_nfeCabecMsg);
	        logger.info("nfeStatusServico2.result=" + _nfeStatusServico2__return);
	
	        
//        }
//        catch(Exception e)
//        {
//        	logger.error("error ",e);
//        }
        return  _nfeStatusServico2__return.toString();
    }

}
