
package br.com.hs.cte.ws.sc.homo.cteconsulta;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import org.apache.cxf.configuration.jsse.TLSClientParameters;
import org.apache.cxf.endpoint.Client;
import org.apache.cxf.frontend.ClientProxy;
import org.apache.cxf.jaxws.JaxWsProxyFactoryBean;
import org.apache.cxf.transport.http.HTTPConduit;
import org.apache.cxf.xmlbeans.XmlBeansDataBinding;
import org.apache.log4j.Logger;

import br.com.hs.nfe.entity.Estabelecimento;
import br.com.hs.nfe.util.ClientConfig;

/**
 * This class was generated by Apache CXF 2.2.1
 * Wed Sep 28 15:09:44 BRT 2011
 * Generated source version: 2.2.1
 * 
 */

public final class CteConsultaHelper {

	private static final Logger logger = Logger.getLogger("CteConsultaHelper");
    private ClientConfig clientConfig = null;

    public CteConsultaHelper(Estabelecimento config) {
    	this.clientConfig = new ClientConfig(config);
    }

    public String cteConsultaCT(String xml) throws Exception {
    	
    	TLSClientParameters tls = new TLSClientParameters();
        try
        {
        	this.clientConfig.configTLS(tls);
        }
        catch(Exception e)
        {
        	logger.error("error ",e);
        }
      
        JaxWsProxyFactoryBean factory = new JaxWsProxyFactoryBean();
        factory.setServiceClass(CteConsultaSoap12.class);
        factory.setAddress("https://homologacao.cte.sefaz.rs.gov.br/ws/cteconsulta/cteconsulta.asmx");
        factory.setWsdlURL(CteConsulta.WSDL_LOCATION.toString());
        factory.setServiceName(CteConsulta.SERVICE);
        factory.setEndpointName(CteConsulta.CteConsultaSoap12);
        factory.getServiceFactory().setDataBinding(new XmlBeansDataBinding());
        CteConsultaSoap12 port = (CteConsultaSoap12)factory.create();
        Client client = ClientProxy.getClient(port);
        HTTPConduit http = (HTTPConduit)client.getConduit();
        http.setTlsClientParameters(tls);
        br.inf.portalfiscal.cte.wsdl.cteConsulta.CteConsultaCTResultDocument _cteConsultaCT__return = null;
        try{
	        logger.info("Invoking cteConsultaCT...");
	        xml = xml.substring(xml.indexOf("?>")+2);
	        xml = "<?xml version=\"1.0\" encoding=\"utf-8\"?><cteDadosMsg xmlns=\"http://www.portalfiscal.inf.br/cte/wsdl/CteConsulta\">"+xml+"</cteDadosMsg>";
	        br.inf.portalfiscal.cte.wsdl.cteConsulta.CteDadosMsgDocument _cteConsultaCT_cteDadosMsg = br.inf.portalfiscal.cte.wsdl.cteConsulta.CteDadosMsgDocument.Factory.parse(xml);
	        br.inf.portalfiscal.cte.wsdl.cteConsulta.CteCabecMsgDocument cteConsultaCT_cteCabecMsg = br.inf.portalfiscal.cte.wsdl.cteConsulta.CteCabecMsgDocument.Factory.newInstance();
	        br.inf.portalfiscal.cte.wsdl.cteConsulta.CteCabecMsg _cteConsultaCT_cteCabecMsgVal = br.inf.portalfiscal.cte.wsdl.cteConsulta.CteCabecMsg.Factory.newInstance();
	        
	        _cteConsultaCT_cteCabecMsgVal.setVersaoDados("1.03");
	        _cteConsultaCT_cteCabecMsgVal.setCUF("42");
	        cteConsultaCT_cteCabecMsg.setCteCabecMsg(_cteConsultaCT_cteCabecMsgVal);
	        
	        javax.xml.ws.Holder<br.inf.portalfiscal.cte.wsdl.cteConsulta.CteCabecMsgDocument> _cteConsultaCT_cteCabecMsg = new javax.xml.ws.Holder<br.inf.portalfiscal.cte.wsdl.cteConsulta.CteCabecMsgDocument>(cteConsultaCT_cteCabecMsg);
	        
	        _cteConsultaCT__return = port.cteConsultaCT(_cteConsultaCT_cteDadosMsg, _cteConsultaCT_cteCabecMsg);
	        logger.info("cteConsultaCT.result=" + _cteConsultaCT__return);
	
        
	    }
	    catch(Exception e)
	    {
	    	logger.error("error ",e);
	    }
	    return _cteConsultaCT__return.toString();
        
    }

}
