package br.com.hs.nfe.ws.pe.homo.recepcaoevento;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebParam.Mode;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;

/**
 * This class was generated by Apache CXF 2.2.1
 * Tue Nov 01 10:15:09 BRST 2011
 * Generated source version: 2.2.1
 * 
 */
 
@WebService(targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/RecepcaoEvento", name = "RecepcaoEventoSoap12")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface RecepcaoEventoSoap12 {

    @WebResult(name = "nfeRecepcaoEventoResult", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/RecepcaoEvento", partName = "nfeRecepcaoEventoResult")
    @WebMethod(action = "http://www.portalfiscal.inf.br/nfe/wsdl/RecepcaoEvento/nfeRecepcaoEvento")
    public br.inf.portalfiscal.nfe.wsdl.recepcaoEvento.NfeRecepcaoEventoResultDocument nfeRecepcaoEvento(
        @WebParam(partName = "nfeDadosMsg", name = "nfeDadosMsg", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/RecepcaoEvento")
        br.inf.portalfiscal.nfe.wsdl.recepcaoEvento.NfeDadosMsgDocument nfeDadosMsg,
        @WebParam(partName = "nfeCabecMsg", mode = WebParam.Mode.INOUT, name = "nfeCabecMsg", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/RecepcaoEvento", header = true)
        javax.xml.ws.Holder<br.inf.portalfiscal.nfe.wsdl.recepcaoEvento.NfeCabecMsg> nfeCabecMsg
    );
}
