package br.com.hs.nfe.ws.go.homo.nferetrecepecao2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;

/**
 * This class was generated by Apache CXF 2.2.1
 * Mon Oct 31 17:43:19 BRST 2011
 * Generated source version: 2.2.1
 * 
 */
 
@WebService(targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeRetRecepcao2", name = "NfeRetRecepcaoService")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface NfeRetRecepcaoService {

    @WebResult(name = "nfeRetRecepcao2Result", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeRetRecepcao2", partName = "nfeRetRecepcao2Result")
    @WebMethod(action = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeRetRecepcao2/nfeRetRecepcao2")
    public br.inf.portalfiscal.nfe.wsdl.nfeRetRecepcao2.NfeRetRecepcao2ResultDocument nfeRetRecepcao2(
        @WebParam(partName = "nfeCabecMsg", name = "nfeCabecMsg", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeRetRecepcao2", header = true)
        br.inf.portalfiscal.nfe.wsdl.nfeRetRecepcao2.NfeCabecMsg nfeCabecMsg,
        @WebParam(partName = "nfeDadosMsg", name = "nfeDadosMsg", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeRetRecepcao2")
        br.inf.portalfiscal.nfe.wsdl.nfeRetRecepcao2.NfeDadosMsgDocument nfeDadosMsg
    );
}
