
package br.com.hs.nfe.ws.br.homo.sceconsultarfb;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import org.apache.cxf.configuration.jsse.TLSClientParameters;
import org.apache.cxf.endpoint.Client;
import org.apache.cxf.frontend.ClientProxy;
import org.apache.cxf.jaxws.JaxWsProxyFactoryBean;
import org.apache.cxf.transport.http.HTTPConduit;
import org.apache.cxf.xmlbeans.XmlBeansDataBinding;
import org.apache.log4j.Logger;

import br.com.hs.nfe.entity.Estabelecimento;
import br.com.hs.nfe.util.ClientConfig;

/**
 * This class was generated by Apache CXF 2.2.1
 * Sun Aug 28 20:55:23 BRT 2011
 * Generated source version: 2.2.1
 * 
 */

public final class SCEConsultaRFBHelper {
	
	private static final Logger logger = Logger.getLogger("SCEConsultaRFBHelper");
    private ClientConfig clientConfig = null;

    public SCEConsultaRFBHelper(Estabelecimento config) {
    	this.clientConfig = new ClientConfig(config);
    }

    public String sceConsultaRFB(String nome,String xml) throws Exception {
    	//System.setProperty("javax.net.debug", "all");
        TLSClientParameters tls = new TLSClientParameters();
        try
        {
        	this.clientConfig.configTLS(tls);
        }
        catch(Exception e)
        {
        	logger.error("error ",e);
        }
        JaxWsProxyFactoryBean factory = new JaxWsProxyFactoryBean();
        factory.setServiceClass(SCEConsultaRFBSoap.class);
        factory.setAddress("https://hom.nfe.fazenda.gov.br/SCEConsultaRFB/SCEConsultaRFB.asmx");
        factory.setWsdlURL(SCEConsultaRFB.WSDL_LOCATION.toString());
        factory.setServiceName(SCEConsultaRFB.SERVICE);
        factory.setEndpointName(SCEConsultaRFB.SCEConsultaRFBSoap);
        factory.getServiceFactory().setDataBinding(new XmlBeansDataBinding());
        SCEConsultaRFBSoap port = (SCEConsultaRFBSoap)factory.create();
        Client client = ClientProxy.getClient(port);
        HTTPConduit http = (HTTPConduit)client.getConduit();
        http.setTlsClientParameters(tls);
        br.inf.portalfiscal.nfe.wsdl.sceConsultaRFB.SceConsultaDPECResultDocument _sceConsultaDpec__return = null;
        try{
	        logger.info("Invoking sceConsultaDpec...");
	        xml = xml.substring(xml.indexOf("?>")+2);
	        xml = "<?xml version=\"1.0\" encoding=\"utf-8\"?><sceDadosMsg xmlns=\"http://www.portalfiscal.inf.br/nfe/wsdl/SCEConsultaRFB\">"+xml+"</sceDadosMsg>";
	        br.inf.portalfiscal.nfe.wsdl.sceConsultaRFB.SceDadosMsgDocument _sceConsultaDpec_dpecDadosMsg = br.inf.portalfiscal.nfe.wsdl.sceConsultaRFB.SceDadosMsgDocument.Factory.parse(xml);
	        br.inf.portalfiscal.nfe.wsdl.sceConsultaRFB.SceCabecMsgDocument sceConsultaDpec_dpecCabecMsg = br.inf.portalfiscal.nfe.wsdl.sceConsultaRFB.SceCabecMsgDocument.Factory.newInstance();
	        br.inf.portalfiscal.nfe.wsdl.sceConsultaRFB.SceCabecMsg _sceConsultaDpec_dpecCabecMsgVal = br.inf.portalfiscal.nfe.wsdl.sceConsultaRFB.SceCabecMsg.Factory.newInstance();
	        _sceConsultaDpec_dpecCabecMsgVal.setVersaoDados("1.01");
	        sceConsultaDpec_dpecCabecMsg.setSceCabecMsg(_sceConsultaDpec_dpecCabecMsgVal);
	        javax.xml.ws.Holder<br.inf.portalfiscal.nfe.wsdl.sceConsultaRFB.SceCabecMsgDocument> _sceConsultaDpec_dpecCabecMsg = new javax.xml.ws.Holder<br.inf.portalfiscal.nfe.wsdl.sceConsultaRFB.SceCabecMsgDocument>(sceConsultaDpec_dpecCabecMsg);
	        _sceConsultaDpec__return = port.sceConsultaDPEC(_sceConsultaDpec_dpecDadosMsg, _sceConsultaDpec_dpecCabecMsg);
	        logger.info("sceConsultaDpec.result=" + _sceConsultaDpec__return);
	
	        logger.info("sceConsultaDpec._sceConsultaDpec_dpecCabecMsg=" + _sceConsultaDpec_dpecCabecMsg.value);
	        
        }
        catch(Exception e)
        {
        	logger.error("error ",e);
        }
        return  _sceConsultaDpec__return.toString();
    }

}
