package br.com.hs.nfe.ws.br.homo.scerecepcaorfb;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 2.2.1
 * Sun Aug 28 20:55:09 BRT 2011
 * Generated source version: 2.2.1
 * 
 */
 
@WebService(targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/SCERecepcaoRFB", name = "SCERecepcaoRFBSoap")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SCERecepcaoRFBSoap {

    @WebResult(name = "sceRecepcaoDPECResult", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/SCERecepcaoRFB", partName = "sceRecepcaoDPECResult")
    @WebMethod(action = "http://www.portalfiscal.inf.br/nfe/wsdl/SCERecepcaoRFB/sceRecepcaoDPEC")
    public br.inf.portalfiscal.nfe.wsdl.sceRecepcaoRFB.SceRecepcaoDPECResultDocument sceRecepcaoDPEC(
        @WebParam(partName = "sceDadosMsg", name = "sceDadosMsg", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/SCERecepcaoRFB")
        br.inf.portalfiscal.nfe.wsdl.sceRecepcaoRFB.SceDadosMsgDocument sceDadosMsg,
        @WebParam(partName = "sceCabecMsg", mode = WebParam.Mode.INOUT, name = "sceCabecMsg", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/SCERecepcaoRFB", header = true)
        javax.xml.ws.Holder<br.inf.portalfiscal.nfe.wsdl.sceRecepcaoRFB.SceCabecMsgDocument> sceCabecMsg
    );
}
