
package br.com.hs.nfe.ws.br.homo.nferecepcaoscan;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */


/**
 * This class was generated by Apache CXF 2.2.1
 * Mon Sep 05 15:03:09 BRT 2011
 * Generated source version: 2.2.1
 * 
 */

public final class NfeRecepcao2Soap_NfeRecepcao2Soap12_Client {

    //private static final QName SERVICE_NAME = new QName("http://www.portalfiscal.inf.br/nfe/wsdl/NfeRecepcao2", "NfeRecepcao2");

    private NfeRecepcao2Soap_NfeRecepcao2Soap12_Client() {
    }

    public static void main(String args[]) throws Exception {
//        URL wsdlURL = NfeRecepcao2.WSDL_LOCATION;
//        if (args.length > 0) { 
//            File wsdlFile = new File(args[0]);
//            try {
//                if (wsdlFile.exists()) {
//                    wsdlURL = wsdlFile.toURI().toURL();
//                } else {
//                    wsdlURL = new URL(args[0]);
//                }
//            } catch (MalformedURLException e) {
//                e.printStackTrace();
//            }
//        }
//      
//        NfeRecepcao2 ss = new NfeRecepcao2(wsdlURL, SERVICE_NAME);
//        NfeRecepcao2Soap port = ss.getNfeRecepcao2Soap12();  
//        
//        {
//        System.out.println("Invoking nfeRecepcaoLote2...");
//        br.inf.portalfiscal.nfe.wsdl.nfeRecepcao2.NfeDadosMsgDocument _nfeRecepcaoLote2_nfeDadosMsg = null;
//        br.inf.portalfiscal.nfe.wsdl.nfeRecepcao2.NfeCabecMsg _nfeRecepcaoLote2_nfeCabecMsg = null;
        //br.inf.portalfiscal.nfe.wsdl.nfeRecepcao2.NfeRecepcaoLote2ResultDocument _nfeRecepcaoLote2__return = port.nfeRecepcaoLote2(_nfeRecepcaoLote2_nfeDadosMsg, _nfeRecepcaoLote2_nfeCabecMsg);
        //System.out.println("nfeRecepcaoLote2.result=" + _nfeRecepcaoLote2__return);


        //}

        //System.exit(0);
    }

}
