
package br.com.hs.nfe.ws.sc.homo.recepcaoevento;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import org.apache.cxf.configuration.jsse.TLSClientParameters;
import org.apache.cxf.endpoint.Client;
import org.apache.cxf.frontend.ClientProxy;
import org.apache.cxf.jaxws.JaxWsProxyFactoryBean;
import org.apache.cxf.transport.http.HTTPConduit;
import org.apache.cxf.xmlbeans.XmlBeansDataBinding;
import org.apache.log4j.Logger;

import br.com.hs.nfe.entity.Estabelecimento;
import br.com.hs.nfe.util.ClientConfig;

/**
 * This class was generated by Apache CXF 2.2.1
 * Tue Oct 25 15:13:59 BRST 2011
 * Generated source version: 2.2.1
 * 
 */

public final class RecepcaoEventoHelper {
	
	private static final Logger logger = Logger.getLogger("RecepcaoEventoHelper");
	private ClientConfig clientConfig = null;
    public RecepcaoEventoHelper(Estabelecimento config) {
    	this.clientConfig = new ClientConfig(config);
    }

    public String nfeRecepcaoEvento(String nome,String xml) throws Exception {
    	TLSClientParameters tls = new TLSClientParameters();
        try
        {
        	this.clientConfig.configTLS(tls);
        }
        catch(Exception e)
        {
        	logger.error("error ",e);
        }
        JaxWsProxyFactoryBean factory = new JaxWsProxyFactoryBean();
        factory.setServiceClass(RecepcaoEventoSoap12.class);
        factory.setAddress("https://homologacao.nfe.sefazvirtual.rs.gov.br/ws/recepcaoevento/recepcaoevento.asmx");
        factory.setWsdlURL(RecepcaoEvento.WSDL_LOCATION.toString());
        factory.setServiceName(RecepcaoEvento.SERVICE);
        factory.setEndpointName(RecepcaoEvento.RecepcaoEventoSoap12);
        factory.getServiceFactory().setDataBinding(new XmlBeansDataBinding());
        RecepcaoEventoSoap12 port = (RecepcaoEventoSoap12)factory.create();
        Client client = ClientProxy.getClient(port);
        HTTPConduit http = (HTTPConduit)client.getConduit();
        http.setTlsClientParameters(tls);
        br.inf.portalfiscal.nfe.wsdl.recepcaoEvento.NfeRecepcaoEventoResultDocument _nfeRecepcaoEvento__return = null;
        
        try{
	        logger.info("Invoking nfeRecepcaoEvento...");
	        xml = xml.substring(xml.indexOf("?>")+2);
	        xml = "<?xml version=\"1.0\" encoding=\"utf-8\"?><nfeDadosMsg xmlns=\"http://www.portalfiscal.inf.br/nfe/wsdl/RecepcaoEvento\">"+xml+"</nfeDadosMsg>";
	        br.inf.portalfiscal.nfe.wsdl.recepcaoEvento.NfeDadosMsgDocument _nfeRecepcaoEvento_nfeDadosMsg = br.inf.portalfiscal.nfe.wsdl.recepcaoEvento.NfeDadosMsgDocument.Factory.parse(xml);
	        br.inf.portalfiscal.nfe.wsdl.recepcaoEvento.NfeCabecMsgDocument nfeRetRecepcaoEvento_nfeCabecMsg = br.inf.portalfiscal.nfe.wsdl.recepcaoEvento.NfeCabecMsgDocument.Factory.newInstance();
	        br.inf.portalfiscal.nfe.wsdl.recepcaoEvento.NfeCabecMsg _nfeRetRecepcaoEvento_nfeCabecMsgVal = br.inf.portalfiscal.nfe.wsdl.recepcaoEvento.NfeCabecMsg.Factory.newInstance();
	        _nfeRetRecepcaoEvento_nfeCabecMsgVal.setCUF("42");
	        _nfeRetRecepcaoEvento_nfeCabecMsgVal.setVersaoDados("1.00");
	        nfeRetRecepcaoEvento_nfeCabecMsg.setNfeCabecMsg(_nfeRetRecepcaoEvento_nfeCabecMsgVal);
	        
	        
	        javax.xml.ws.Holder<br.inf.portalfiscal.nfe.wsdl.recepcaoEvento.NfeCabecMsgDocument> _nfeRetRecepcao2_nfeCabecMsg = new javax.xml.ws.Holder<br.inf.portalfiscal.nfe.wsdl.recepcaoEvento.NfeCabecMsgDocument>(nfeRetRecepcaoEvento_nfeCabecMsg);
	        _nfeRecepcaoEvento__return = port.nfeRecepcaoEvento(_nfeRecepcaoEvento_nfeDadosMsg, _nfeRetRecepcao2_nfeCabecMsg);
	        logger.info("nfeRetRecepcao2.result=" + _nfeRecepcaoEvento__return);

	        logger.info("nfeRetRecepcao2._nfeRetRecepcao2_nfeCabecMsg=" + _nfeRetRecepcao2_nfeCabecMsg.value);

        }
        catch(Exception e)
        {
        	logger.error("error ",e);
        }
        return _nfeRecepcaoEvento__return.toString();
    }
}
