
package br.com.hs.nfe.ws.br.homo.scerecepcaorfb;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import org.apache.cxf.configuration.jsse.TLSClientParameters;
import org.apache.cxf.endpoint.Client;
import org.apache.cxf.frontend.ClientProxy;
import org.apache.cxf.jaxws.JaxWsProxyFactoryBean;
import org.apache.cxf.transport.http.HTTPConduit;
import org.apache.cxf.xmlbeans.XmlBeansDataBinding;
import org.apache.log4j.Logger;

import br.com.hs.nfe.entity.Estabelecimento;
import br.com.hs.nfe.util.ClientConfig;

/**
 * This class was generated by Apache CXF 2.2.1
 * Sun Aug 28 20:55:09 BRT 2011
 * Generated source version: 2.2.1
 * 
 */

public final class SCERecepcaoRFBHelper {

	private static final Logger logger = Logger.getLogger("SCERecepcaoRFBHelper");
    private ClientConfig clientConfig = null;

    public SCERecepcaoRFBHelper(Estabelecimento config) {
    	clientConfig = new ClientConfig(config);
    }

    public String sceRecepcaoDPEC(String nome,String xml) throws Exception {
    	//System.setProperty("javax.net.debug", "all");
        TLSClientParameters tls = new TLSClientParameters();
        try
        {
        	this.clientConfig.configTLS(tls);
        }
        catch(Exception e)
        {
        	logger.error("error ",e);
        }
        JaxWsProxyFactoryBean factory = new JaxWsProxyFactoryBean();
        factory.setServiceClass(SCERecepcaoRFBSoap.class);
        factory.setAddress("https://hom.nfe.fazenda.gov.br/SCERecepcaoRFB/SCERecepcaoRFB.asmx");
        factory.setWsdlURL(SCERecepcaoRFB.WSDL_LOCATION.toString());
        factory.setServiceName(SCERecepcaoRFB.SERVICE);
        factory.setEndpointName(SCERecepcaoRFB.SCERecepcaoRFBSoap);
        factory.getServiceFactory().setDataBinding(new XmlBeansDataBinding());
        SCERecepcaoRFBSoap port = (SCERecepcaoRFBSoap)factory.create();
        Client client = ClientProxy.getClient(port);
        HTTPConduit http = (HTTPConduit)client.getConduit();
        http.setTlsClientParameters(tls);
        br.inf.portalfiscal.nfe.wsdl.sceRecepcaoRFB.SceRecepcaoDPECResultDocument _sceRecepcaoDpec__return = null;
        try{
	        logger.info("Invoking sceRecepcaoDpec...");
	        xml = xml.substring(xml.indexOf("?>")+2);
	        xml = "<?xml version=\"1.0\" encoding=\"utf-8\"?><sceDadosMsg xmlns=\"http://www.portalfiscal.inf.br/nfe/wsdl/SCERecepcaoRFB\">"+xml+"</sceDadosMsg>";
	        br.inf.portalfiscal.nfe.wsdl.sceRecepcaoRFB.SceDadosMsgDocument _sceRecepcaoDpec_dpecDadosMsg = br.inf.portalfiscal.nfe.wsdl.sceRecepcaoRFB.SceDadosMsgDocument.Factory.parse(xml);
	        br.inf.portalfiscal.nfe.wsdl.sceRecepcaoRFB.SceCabecMsgDocument sceRecepcaoDpec_dpecCabecMsg = br.inf.portalfiscal.nfe.wsdl.sceRecepcaoRFB.SceCabecMsgDocument.Factory.newInstance();
	        br.inf.portalfiscal.nfe.wsdl.sceRecepcaoRFB.SceCabecMsg _sceRecepcaoDpec_dpecCabecMsgVal = br.inf.portalfiscal.nfe.wsdl.sceRecepcaoRFB.SceCabecMsg.Factory.newInstance();
	        _sceRecepcaoDpec_dpecCabecMsgVal.setVersaoDados("1.01");
	        sceRecepcaoDpec_dpecCabecMsg.setSceCabecMsg(_sceRecepcaoDpec_dpecCabecMsgVal);
	        javax.xml.ws.Holder<br.inf.portalfiscal.nfe.wsdl.sceRecepcaoRFB.SceCabecMsgDocument> _sceRecepcaoDpec_dpecCabecMsg = new javax.xml.ws.Holder<br.inf.portalfiscal.nfe.wsdl.sceRecepcaoRFB.SceCabecMsgDocument>(sceRecepcaoDpec_dpecCabecMsg);
	        _sceRecepcaoDpec__return = port.sceRecepcaoDPEC(_sceRecepcaoDpec_dpecDadosMsg, _sceRecepcaoDpec_dpecCabecMsg);
	        logger.info("sceRecepcaoDpec.result=" + _sceRecepcaoDpec__return);
	
	        logger.info("sceRecepcaoDpec._sceRecepcaoDpec_dpecCabecMsg=" + _sceRecepcaoDpec_dpecCabecMsg.value);
	        
        }
        catch(Exception e)
        {
        	logger.error("error ",e);
        }
        return  _sceRecepcaoDpec__return.toString();
    }
}
