package br.com.hs.nfe.ws.svan.prod.recepcaoevento;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;

/**
 * This class was generated by Apache CXF 2.2.1
 * Tue Nov 01 11:54:12 BRST 2011
 * Generated source version: 2.2.1
 * 
 */
 
@WebService(targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/RecepcaoEvento", name = "RecepcaoEventoSoap")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface RecepcaoEventoSoap {

    @WebResult(name = "nfeRecepcaoEventoResult", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/RecepcaoEvento", partName = "nfeRecepcaoEventoResult")
    @WebMethod(action = "http://www.portalfiscal.inf.br/nfe/wsdl/RecepcaoEvento/nfeRecepcaoEvento")
    public br.inf.portalfiscal.nfe.wsdl.recepcaoEvento.NfeRecepcaoEventoResultDocument nfeRecepcaoEvento(
        @WebParam(partName = "nfeDadosMsg", name = "nfeDadosMsg", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/RecepcaoEvento")
        br.inf.portalfiscal.nfe.wsdl.recepcaoEvento.NfeDadosMsgDocument nfeDadosMsg,
        @WebParam(partName = "nfeCabecMsg", name = "nfeCabecMsg", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/RecepcaoEvento", header = true)
        br.inf.portalfiscal.nfe.wsdl.recepcaoEvento.NfeCabecMsg nfeCabecMsg
    );
}
